CommonsDev/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Commons.Controllers;
using Commons.Extensions;
using Commons.Identity;
using Commons.Identity.Attributes;
using Commons.Identity.Extensions;
using Commons.Identity.Services;
using Commons.Models;
using CommonsDev.Data;
using Microsoft.AspNetCore.Mvc;
using CommonsDev.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace CommonsDev.Controllers
{
    [Secured]
    public class HomeController : CommonsController
    {
        private readonly IRolesService _roles;
        private readonly UserService<User> _user;
        private readonly ApplicationDbContext _context;
        private readonly IClaimsService _claims;
        private IHttpContextAccessor _http;

        public HomeController(ApplicationDbContext context,
            IRolesService roles,
            UserService<User> user,
            IClaimsService claims,
            IHttpContextAccessor http)
        {
            _roles = roles;
            _user = user;
            _context = context;
            _claims = claims;
            _http = http;
        }

        [Unsecured]
        public async Task<IActionResult> Index([FromServices] UserService<User> userService, int nro = 0)
        {
            ViewBag.Nro = nro + 1;
            ViewBag.UserId = userService.FindByNameAsync(User.Identity.Name).Result.Id;


            var user = await _user.FindByNameAsync(User.GetUserName());

            AddPageAlerts(PageAlertType.Info, $"Username {user.UserName}");

            //var routes = await HttpContext.GetUserRoutes();
            var routes = new List<string>();


            if (User.IsInRole("47a29155-98ac-4a63-879c-4a827e782f81: Test"))
            {
                AddPageAlerts(PageAlertType.Success, "Esta en el rol de testing.");
            }



            ViewBag.Routes = routes;

            AddBreadcrumb($"Primero", $"/Home/", $"fa fa-circle");
            AddBreadcrumb($"Primero", $"/Home/", $"fa fa-circle");
            AddBreadcrumb($"Primero", $"/Home/", $"fa fa-circle");
            AddBreadcrumb($"Primero", $"/Home/", $"fa fa-circle");

            return View();
        }

        public IActionResult ErrorAsync()
        {
            return BadRequest("Mensaje de error que da el controlador.");
        }

        public IActionResult _Partial()
        {
            return PartialView();
        }

        
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        /// <summary>
        /// Returns partial view for role assignment.
        /// </summary>
        /// <param name="id">User id.</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> _Assign(string id)
        {
            var userRoles = await _user.GetRoles(id, User.GetWorkSpaceId());
            ViewBag.UserRoles = userRoles;

            var roles = await _roles.GetRoles(x => x.WorkSpaceId == User.GetWorkSpaceId());

            roles.RemoveAll(x => userRoles.Contains(x));

            ViewBag.Roles = roles.Select(x => new SelectListItem(x.ShowName, x.Id));
            ViewBag.IsAdmin = _claims.IsWorkSpaceAdmin(id, User.GetWorkSpaceId());
            return PartialView("_Assign", id);
        }

        public IActionResult SelectListJson(string q)
        {
            var items = _context.Tests.Where(x => x.Name.Contains(q))
                .Select(x => new 
                {
                    Text = $"{x.Name}, {x.Doc}",
                    Value = x.Id,
                    Subtext = $"{x.Doc} {x.Doc}",
                    Icon = "fa fa-plus",
                    Class = ""
                }).Take(50).ToArray();

            return Json(items);
        }


        [Secured]
        public async Task<IActionResult> SelectListJson2(string q)
        {
            var items = await _context.Tests.Where(x => x.Name.Contains(q))
                .Select(x => new SelectpickerItem()
                {
                    Text = x.Name,
                    Value = x.Id,
                    Subtext = x.Doc,
                    Icon = "fa fa-plus",
                    //Content = "<small class=\"label label-success\">Sí</small>"
                }).Take(10).ToArrayAsync();

            return Json(items);
        }


        private static Random random = new Random();
        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        public async Task<IActionResult> GenerateRandomFunctions()
        {
            var routes = new List<CommonsRoute>();

            for (int i = 0; i < 1000; i++)
            {
                routes.Add(new CommonsRoute()
                {
                    Area = RandomString(10),
                    Controller = RandomString(10),
                    Action = RandomString(10)
                });
            }

            var function = new CommonsFunction(){
                Name = $"1000 routes function {RandomString(3)}",
            };

            function.SetRoutes(routes);

            _context.AspNetFunctions.Add(function);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public IActionResult DoubleModal()
        {
            return PartialView("DoubleModal");
        }

        public IActionResult TripleModal()
        {
            return PartialView("TripleModal");
        }

        public IActionResult Bool(bool uno, bool dos)
        {
            return Json(new {uno = uno, dos = dos});
        }
        
        [HttpGet]
        public IActionResult File()
        {
            return PartialView();
        }
        
        [HttpPost]
        public IActionResult File(IFormFile file)
        {
            throw new Exception(file.Name);
        }

        [HttpGet]
        public IActionResult _ModalError()
        {
            return PartialView("_ModalError", "Mensaje de error.");
        }
    }
}

CommonsDev/Controllers/ModalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CommonsDev.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CommonsDev.Controllers
{
    public class ModalsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ModalsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult _HeavyPartial()
        {
            return PartialView();
        }

        public IActionResult _LoadersTest()
        {
            return PartialView();
        }

        public IActionResult _ComboBox()
        {
            ViewBag.Items = _context.Institutes.Take(30).Select(x => new SelectListItem(x.Name, x.Id));
            
            return PartialView();
        }


        public IActionResult _Embed(string param)
        {
            ViewBag.File = "data:application/pdf;base64," + Convert.ToBase64String(System.IO.File.ReadAllBytes("wwwroot/docs/archivo.pdf"));
            return PartialView();
        }

        public IActionResult _Embed2(string param)
        {
            ViewBag.File = "data:application/pdf;base64," + Convert.ToBase64String(System.IO.File.ReadAllBytes("wwwroot/docs/archivo.pdf"));
            return PartialView();
        }

        public IActionResult Pdf()
        {
            var bytes = System.IO.File.ReadAllBytes("wwwroot/docs/archivo.pdf");

            return File(bytes, "application/pdf");
        }
    }
}

CommonsDev/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Modals functions test";
}

<!--
    DEBUG MODAL
-->

<h3>Debug Modal</h3>
<a class="btn btn-danger" onclick="Create()">Click me!</a>

<script src="~/js/commons_modals_debug.js"></script>

<div class="modal fade in" id="CreateModal" style="display: none;">
    <div class="modal-dialog ">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Nueva funcion</h4>
            </div>

            <div class="holder" style="min-height: 250px">
                <div class="preloader">
                    <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
                </div>
                <h4 class="preloader-text"></h4>
            </div>

            <div class="modal-body " style="">

            </div>
        </div>
    </div>
    <script type="text/javascript">
        function Create(id) {
            LoadModalDebug('#CreateModal', '@Url.Action("_Embed2", "Modals")/');
        };
    </script>
</div>


<!--
Doble answer Modal
-->

<h3>Doble answer Modal</h3>
<a class="btn btn-primary" onclick="LoadedModal()">Click me!</a>

<modal load-text="asdad" callback-modal="true" title="Loaded Modal" function="LoadedModal" load-url="/Home/Contact"></modal>




<!--
Static Modal
-->

<h3>Modal with static content</h3>
<a class="btn btn-info" onclick="StaticModal()">Click me!</a>

<modal title="Static Modal" function="StaticModal">

    Static Content Here

</modal>


<!--
Modal that calls another modal
-->

<h3>Modal that calls another modal</h3>
<a onclick="doubleModal()" class="btn btn-info">Click me!</a>

<modal function="doubleModal" load-url="@Url.Action("DoubleModal")" title="DoubleModal"></modal>

<modal function="tripleModal" load-url="@Url.Action("TripleModal")" title="Triple Modal"></modal>



<!--
Loaders test
-->

<h3>Loaders test</h3>
<a class="btn btn-primary" onclick="Loaders()">Click me!</a>

<modal load-text="Loading original modal" callback-modal="true" title="Loaders" function="Loaders" load-url="/Modals/_LoadersTest"></modal>


<!--
ComboBox Modal
-->

<h3>ComboBox Modal</h3>
<a class="btn btn-primary" onclick="Combo()">Click me!</a>

<modal load-text="Loading combo modal" title="Combo" function="Combo" load-url="/Modals/_ComboBox"></modal>

<!--
Embee Modal
-->

<h3>Embed Modal</h3>
<a class="btn btn-primary" onclick="Embed()">Click me!</a>

<modal load-text="Loading embed modal" title="Embed" function="Embed" load-url="/Modals/_Embed"></modal>


<!--
Embee Modal with second call
-->

<h3>Embed Modal with second call</h3>
<a class="btn btn-primary" onclick="Embed2()">Click me!</a>

<modal load-text="Loading embed modal w 2d call" title="Embed2" function="Embed2" load-url="/Modals/_Embed2"></modal>

CommonsDev/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "";
}






<div class="row">
    <div class="col-md-12">
        <h2>@ViewData["Title"]</h2>
        <h3>@ViewData["Message"]</h3>
        @*<img src="https://wallpaperplay.com/walls/full/d/9/b/44840.jpg" height="5px" />*@
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <h3>Form vista total</h3>
        <form asp-action="Privacy">
            <input name="id" type="hidden" value="123"/>
    
            <input name="bool" type="checkbox"/>
            <br />
            <button class="btn btn-danger" type="submit">Aceptar</button>
        </form>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <h3>Form vista parcial</h3>
        <form data-loader-text="Testo" asp-action="_Partial" method="post">
            <input name="id" type="hidden" value="123"/>
    
            <input name="bool" type="checkbox"/>
            <br />
            <button class="btn btn-info" type="submit">Aceptar</button>
        </form>
    </div>
</div>

CommonsDev/Views/Home/DoubleModal.cshtml
@model object



DoubleModal

<a onclick="tripleModal()" class="btn btn-block btn-info">Triple Modal</a>

CommonsDev/Views/Home/File.cshtml
<form asp-action="File" enctype="multipart/form-data">
    <input type="file" class="form-control" name="file"/>
    <button type="submit">Aceptar</button>
</form>

CommonsDev/Views/Home/Index.cshtml
@using Commons.Identity
@model CommonsDev.Data.Institute
@{
    ViewData["Title"] = "Commons Framework Tests";
}

<style>
</style>

<form asp-action="Bool">
    <box>
        <box-header title="iCheck" minimize="true" close="true"></box-header>
        <box-body>

            <div class="form-group">
                <input asp-for="ThisIsBool" type="checkbox" />
            </div>
            <div class="form-group">
                <input color="Danger" type="checkbox" name="2" id="2" />
                <label for="2">2</label>
            </div>
            <div class="form-group">
                <input type="radio" name="iCheck">
                <label>1</label>
            </div>
            <div class="form-group">
                <input type="radio" name="iCheck" checked>
                <label>1</label>
            </div>
        </box-body>
        <box-footer>
            <button class="btn btn-info pull-right" type="submit">Send</button>
        </box-footer>
    </box>
</form>

<box>
    <box-header title="Mis permisos"></box-header>
    <box-body>
        <table id="perTable" class="table table-striped table-bordered dt-responsive nowrap">
            <thead>
                <tr>
                    <th>
                        Route
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (string route in (ViewBag.Routes ?? new List<string>()))
                {
                    <tr>
                        <td>
                            @route
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </box-body>
    <box-footer>
        <a asp-action="GenerateRandomFunctions">Generar random function</a>
    </box-footer>
</box>

<script>
    $(document).ready(function () {
        $('#perTable').DataTable();
    });
</script>

<box color="Info">
    <box-header title="Selects" minimize="true" close="true"></box-header>

    <box-body>
        <h4 class="text-muted">Simple Selectpicker</h4>
        <select title="Elegir una opcion:"
                class="form-control pull-right"
                searchable="false"
                menu-header="Header"
                color="Success"
                multiple-max-options="2">
            <option value="volvo">Volvo</option>
            <option value="saab">Saab</option>
            <option value="mercedes">Mercedes</option>
            <option value="audi">Audi</option>
        </select>

        <br />
        <br />

        <h4 class="text-muted">Commons Ajax Selecktpicker</h4>
        <select-ajax title="Fully customizable"
                     class="form-control"
                     url="@Url.Action("SelectListJson")"
                     color="Info"
                     menu-size="10"
                     multiple-max-options="2"
                     class-btn="btn-flat"
                     text-no-results="Oh no! No encontraste nada!"
                     text-initialized="Ejem... Estamos esperando que escribas algo..."
                     text-placeholder="Acá es donde tenés que escribir... duh!"
                     route-name="q">
        </select-ajax>

        <br />
        <br />

        <h4 class="text-muted">Ajax search selectpicker</h4>

        <select class="with-ajax"
                id="selectpicker"
                title="test"
                menu-header="Header"
                searchable="true"
                class-btn="btn-sm btn-flat"
                color="Primary"></select>

        <script>


            var options = {
                values: "a, b, c",
                ajax: {
                    url: "@Url.Action("SelectListJson2")",
                    type: "POST",
                    dataType: "json",
                    // Use "{{{q}}}" as a placeholder and Ajax Bootstrap Select will
                    // automatically replace it with the value of the search query.
                    data: {
                        q: "{{{q}}}"
                    }
                },
                locale: {
                    //emptyTitle: "",
                    statusSearching: "Buscando coincidencias...",
                    statusNoResults: "No se encontraron coincidencias.",
                    statusInitialized: "Escriba un texto para buscar...",
                    searchPlaceholder: "Placeholder",
                    currentlySelected: "Seleccionado"
                },
                log: 3,
                preprocessData: function(data) {
                    var i,
                        l = data.length,
                        array = [];
                    if (l) {
                        for (i = 0; i < l; i++) {
                            array.push(
                                $.extend(true, data[i], {
                                    text: data[i].Text,
                                    value: data[i].Value,
                                    class: data[i].Class,
                                    disabled: data[i].Disabled,
                                    divider: data[i].Divider,
                                    data: {
                                        subtext: data[i].Subtext,
                                        content: data[i].Content,
                                        icon: data[i].Icon
                                    }
                                })
                            );
                        }
                    }
                    // You must always return a valid array when processing data. The
                    // data argument passed is a clone and cannot be modified directly.
                    return array;
                }
            };

            $("#selectpicker")
                .selectpicker()
                .filter(".with-ajax")
                .ajaxSelectPicker(options);
            $("select").trigger("change");

            function chooseSelectpicker(index, selectpicker) {
                $(selectpicker).val(index);
                $(selectpicker).selectpicker('refresh');
            }


        </script>

    </box-body>

</box>


<box color="Info">
    <box-header title="Request loaded box" minimize="true" close="true"></box-header>

    <box-body>
        <div class="row">
            <div class="col-md-6">

                <a href="/Home?nro=@ViewBag.Nro"
                   title="test"
                   confirm="¿Está seguro de que este framework funciona correctamente?"
                   confirm-yes="Sí"
                   confirm-no="No"
                   confirm-title="¿Vos decís?"
                   confirm-icon="Danger"
                   data-conf="Estoy pisando el otro texto. Comentame."
                   class="btn btn-primary btn-lg">
                    Confirm modal: Suma 1 a la cuenta
                </a>

            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-aqua"><i class="fa fa-user"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">Cuenta</span>
                                <span class="info-box-number">@ViewBag.Nro<small></small></span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                </div>
            </div>
        </div>
    </box-body>

    <box-footer>
        <a class="btn btn-success"
           ajax-update-div="#testAjax"
           ajax-mode="Before"
           asp-action="_Partial"
           data-conf="Test conf dataajax">
            Llamada de ajax: Modo before
        </a>
    </box-footer>
</box>



<div id="testAjax"></div>
<load load-url="/Home/_Partial"></load>

<div class="text-center">
    <a class="btn btn-primary btn-flat btn-lg" onclick="EditRoles('@ViewBag.UserId')">Editar Roles del usuario logeado test</a>
</div>

<modal title="Editar roles" function="EditRoles" load-url="@Url.Action("_Assign", "SecurityRoles")"></modal>

<br />
<br />

<a onclick="file()" data-conf="Test de conf en caso de ajax." class="btn btn-primary">UploadFile</a>

<modal function="file" load-url="@Url.Action("File")"></modal>

<br />
<br />



<box color="Info">
    <box-header title="Modal Error PartialView" minimize="true" close="true"></box-header>

    <box-body>
        <a class="btn btn-danger" onclick="error()">Modal Error</a>

    </box-body>
</box>
        <modal title="Modal test" function="error" load-url="@Url.Action("_ModalError")"></modal>

CommonsDev/Views/Home/TripleModal.cshtml
<partial name="DoubleModal"/>
<partial name="DoubleModal"/>
<partial name="DoubleModal"/>

CommonsDev/Views/Home/_Assign.cshtml
@using Commons.Identity
@model string
@addTagHelper *, Commons
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    List<CommonsRole> userRolesList = (List<CommonsRole>)ViewBag.UserRoles;
}

<div id="assignDiv">
    <div class="row">
        <div class="col-md-12 ">
            @if (userRolesList == null || !userRolesList.Any())
            {
                <span class="text-muted">
                    <p style="text-align: center; margin: 0">No tiene roles asignados.</p>
                </span>
            }
            else
            {
                <table class="table table-striped table-responsive table-hover">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>
                                <div class="btn-group">
                                    <a href="#" data-toggle="dropdown">
                                        <i class="fa fa-gear"></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-action="_MakeAdmin"
                                               asp-controller="SecurityRoles"
                                               asp-route-userId="@Model"
                                               data-ajax="true"
                                               data-ajax-method="GET"
                                               data-ajax-mode="replace"
                                               data-ajax-update="#assignDiv">
                                            Convertir en administrador
                                        </a></li>
                                    </ul>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var role in userRolesList)
                        {
                            <tr>
                                <td>@role.ShowName</td>
                                <td>@role.Description</td>
                                <td>
                                    <a asp-action="_Unassign"
                                       asp-route-userId="@Model"
                                       asp-route-roleId="@role.Id"
                                       data-ajax="true"
                                       data-ajax-method="GET"
                                       data-ajax-mode="replace"
                                       data-ajax-update="#assignDiv">
                                        <i class="fa fa-remove"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>

    </div>

    <br />

    <div class="row">
        <div class="col-md-12">
            <form asp-action="_Assign"
                  data-ajax="true"
                  data-ajax-method="POST"
                  data-ajax-mode="replace"
                  data-ajax-update="#assignDiv">
                <div class="input-group">
                    <input type="hidden" name="userId" value="@Model" />
                    <select class="form-control flat" title="Asignar nuevo rol..." data-width="100%" name="roleId" asp-items="@ViewBag.Roles"></select>
                    <div class="input-group-btn">
                        <button class="btn btn-default pull-right btn-flat btn-info" type="submit"><i class="fa fa-plus"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
</div>

CommonsDev/Views/Home/_Partial.cshtml
@model object



<img src="https://wallpaperplay.com/walls/full/d/9/b/44840.jpg" height="5px" />
<box>
    <box-header title="Async loaded minimize test" minimize="true" close="true">
    </box-header>
    <box-body class="text-center">
        <a href="/Home"
           confirm="¿Está seguro de que llamo este botón que ha sido cargado desde una partial async?"
           class="btn btn-default btn-lg">
            Async loaded button with confirm
        </a>
    </box-body>
</box>