CommonsDev/Controllers/InstitutesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Commons.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CommonsDev.Data;
using DataTablesParser;

namespace CommonsDev.Controllers
{
    public class InstitutesController : CommonsController
    {
        private readonly ApplicationDbContext _context;

        public InstitutesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Institutes
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // GET: Institutes
        public async Task<IActionResult> DataTable()
        {
            return View();
        }

        public IActionResult Data()
        {
            return DataTable(_context.Institutes.Select(x => new
            {
                Id = x.Id,
                Name = x.Name,
                LongName = x.LongName
            }));
        }

        public IActionResult Data2()
        {
            //var parser = new Parser<Institute>(Request.Form, _context.Institutes.Where(x => true));


            var parser = new Parser<Institute>(Request.Form, _context.Institutes.Where(x => true));

            return Json(parser.Parse());
        }

        // GET: Institutes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institute = await _context.Institutes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (institute == null)
            {
                return NotFound();
            }

            return View(institute);
        }

        public IActionResult RandomInstitutes()
        {
            for (int i = 0; i < 1000; i++)
            {
                var name = RandomString(20);

                _context.Institutes.Add(new Institute()
                {
                    Name = name.PadLeft(5),
                    LongName = name
                });
            }

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: Institutes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Institutes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,LongName")] Institute institute)
        {
            if (ModelState.IsValid)
            {
                _context.Add(institute);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(institute);
        }

        // GET: Institutes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institute = await _context.Institutes.FindAsync(id);
            if (institute == null)
            {
                return NotFound();
            }


            return View(institute);
        }

        // POST: Institutes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,LongName")] Institute institute)
        {
            if (id != institute.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(institute);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstituteExists(institute.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(institute);
        }

        // GET: Institutes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var institute = await _context.Institutes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (institute == null)
            {
                return NotFound();
            }

            return View(institute);
        }

        // POST: Institutes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var institute = await _context.Institutes.FindAsync(id);
            _context.Institutes.Remove(institute);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstituteExists(string id)
        {
            return _context.Institutes.Any(e => e.Id == id);
        }

        private static Random random = new Random();
        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}

CommonsDev/Views/Institutes/Create.cshtml
@model CommonsDev.Data.Institute

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Institute</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongName" class="control-label"></label>
                <input asp-for="LongName" class="form-control" />
                <span asp-validation-for="LongName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommonsDev/Views/Institutes/DataTable.cshtml
@using Commons.HtmlHelpers
@model CommonsDev.Data.Institute

@{
    ViewData["Title"] = "Institutos";
}

<style>
    .table thead > tr > th, .table thead > tr > td {
        border-bottom: 2px solid black;
    }
    .table-bordered {
        border-bottom: 2px solid black;
    }
</style>

<box color="Danger">
    <box-header minimize="true" title="Datatable manual">
    </box-header>
    <box-body table="true">
        <table class="table table-bordered table-responsive" id="PeopleListTable"></table>
    </box-body>
</box>


<script src="https://cdn.datatables.net/fixedheader/3.1.6/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>

<script type="text/javascript">

    $(function() {
        var table = $('#PeopleListTable').DataTable({
            serverSide: true,
            processing: true,



            ajax: {
                url: '@Url.Action("Data2", "Institutes")',
                type: "POST"
            },
            rowId: 'Id',
            columns: [
                { data: "Id", title: "Id" }, { data: "Name", title: "Name" },
                { data: "LongName", title: "Long Name" }, { data: "Test.Name", title: "Navigation" },
                { data: "GimmeFives", title: "Five" }, {
                    "title": "Actions",
                    "sortable": false,
                    "render": function(data, type, row) {
                        var action = '';
                        {
                            action = action +
                                `<a data-toggle="tooltip" title="" data-placement="top" data-original-title="Editar" href=/Institutes/Edit/` +
                                row['Id'] +
                                `><i style='color: red' class='fa fa-edit'></i></a> | `;
                            action = action +
                                @Html.DataTableButton( "/Home/Action/${row['Id']}","asd", "fa fa-edit", BoxColor.Warning);
                        }
                        return action;
                    }
                }, {
                    "title": "Contains a",
                    "sortable": true,
                    "render": function(data, type, row) {
                        if (type === "sort" || type === 'type') {
                            return row.Name;
                        } else {
                            if (row.Name.includes('A')) {
                                return `<span class="label label-success">Sí</span>`;
                            } else {
                                return `<span class="label label-danger">No</span>`;
                            }
                        }
                    }
                },
            ]
        });
        new $.fn.dataTable.FixedHeader(table);
    });


</script>

CommonsDev/Views/Institutes/Delete.cshtml
@model CommonsDev.Data.Institute

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Institute</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LongName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LongName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CommonsDev/Views/Institutes/Details.cshtml
@model CommonsDev.Data.Institute

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Institute</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LongName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LongName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CommonsDev/Views/Institutes/Edit.cshtml
@model CommonsDev.Data.Institute

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Institute</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongName" class="control-label"></label>
                <input asp-for="LongName" class="form-control" />
                <span asp-validation-for="LongName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommonsDev/Views/Institutes/Index.cshtml
@model CommonsDev.Data.Institute

@{
    ViewData["Title"] = "Institutos";
}

<box color="Info">
    <box-header title="Datatable con el framework">
        <a asp-action="RandomInstitutes" class="btn btn-danger btn-sm">Generate random</a>
    </box-header>
    <box-body>

        <data-table class="table table-hover table-bordered table-responsive" url-data="@Url.Action("Data")">
            <data-table-columns>
                <data-table-column property-name="Id"></data-table-column>
                <data-table-column asp-for="Name"></data-table-column>
                <data-table-column asp-for="LongName"></data-table-column>
                <data-table-column asp-for="Test.Name"></data-table-column>
                <data-table-column>
                    <data-table-column-action asp-action="Details" asp-controller="Institutes" title="Detalles">
                        <i class="fa fa-info-circle"></i>
                    </data-table-column-action>
                    <data-table-column-action asp-action="Edit" asp-controller="Institutes" title="Editar">
                        <i class="fa fa-edit"></i>
                    </data-table-column-action>
                    <data-table-column-action asp-action="Delete" asp-controller="Institutes" title="Eliminar">
                        <i class="fa fa-remove"></i>
                    </data-table-column-action>
                </data-table-column>
            </data-table-columns>
        </data-table>

    </box-body>
</box>