CommonsDev/Controllers/ViewComponents/Layout/ControlSidebarViewComponent.cs
using System;
using System.Diagnostics;
using System.IO;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class ControlSidebarViewComponent : ViewComponent
    {

        public ControlSidebarViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            if (string.IsNullOrEmpty(ViewBag.PageHelpFileName))
            {
                return View("LayoutControlSidebar", string.Empty);
            }

            ViewBag.PageHelpContainer = LoadData(ViewBag.PageHelpFileName);
            return View("LayoutControlSidebar");
        }

        private string LoadData(string filepath)
        {
            var basePath = Directory.GetCurrentDirectory() + @"\wwwroot\files\";
            var baseExtension = @".html";
            var absoluteFilePath = basePath + filepath + baseExtension;

            string result = string.Empty;
            try
            {
                if (!File.Exists(absoluteFilePath))
                {
                    return string.Empty;
                }

                using (StreamReader sr = new StreamReader(new FileStream(absoluteFilePath, FileMode.Open, FileAccess.Read)))
                {
                    result = sr.ReadToEnd();
                }
            }
            catch (FileNotFoundException fex)
            {
                Debug.Write(fex);
                return string.Empty;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);
                return string.Empty;
            }

            return result;
        }

        //private List<string> LoadData(string filename)
        //{
        //    var result = new List<string>();
        //    try
        //    {
        //        using (StreamReader sr = new StreamReader(new FileStream(Directory.GetCurrentDirectory() + $"\\wwwroot\\files\\{filename}", FileMode.Open, FileAccess.Read)))
        //        {
        //            var line = string.Empty;
        //            while ((line = sr.ReadLine()) != null)
        //            {
        //                // Adding.
        //                result.Add(line);
        //            }

        //            return result;
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        Debug.Write(ex);
        //    }

        //    return result;
        //}
    }
}

CommonsDev/Controllers/ViewComponents/Layout/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class FooterViewComponent : ViewComponent
    {

        public FooterViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            return View("LayoutFooter");
        }
    }
}

CommonsDev/Controllers/ViewComponents/Layout/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class HeaderViewComponent : ViewComponent
    {

        public HeaderViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            return View("LayoutHeader");
        }
    }
}

CommonsDev/Controllers/ViewComponents/Layout/MenuMessageViewComponent.cs
using System.Collections.Generic;
using Commons.Models;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class MenuMessageViewComponent : ViewComponent
    {

        public MenuMessageViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            var messages = GetData();
            return View("LayoutMenuMessage", messages);
        }

        private List<Message> GetData()
        {
            var messages = new List<Message>();

            messages.Add(new Message
            {
                Id = 1,
                UserId = "",
                DisplayName = "Support Team",
                AvatarURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRxQ-XnyKmKP11SQacp2IutD8Njt89ze2EIIN9AAtrEP5g83jI",
                ShortDesc = "Why not buy a new awesome theme?",
                TimeSpan = "5 mins",
                URLPath = "#",
            });

            messages.Add(new Message
            {
                Id = 1,
                UserId = "",
                DisplayName = "Ken",
                AvatarURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRxQ-XnyKmKP11SQacp2IutD8Njt89ze2EIIN9AAtrEP5g83jI",
                ShortDesc = "For approval",
                TimeSpan = "15 mins",
                URLPath = "#",
            });

            return messages;
        }
    }
}

CommonsDev/Controllers/ViewComponents/Layout/MenuNotificationViewComponent.cs
using System.Collections.Generic;
using Commons.Models;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class MenuNotificationViewComponent : ViewComponent
    {

        public MenuNotificationViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            var messages = GetData();
            return View("LayoutMenuNotification", messages);
        }

        private List<Message> GetData()
        {
            var messages = new List<Message>();
            messages.Add(new Message
            {
                Id = 1,
                FontAwesomeIcon = "fa fa-users text-aqua",
                ShortDesc = "5 new members joined today",
                URLPath = "#",
            });

            return messages;
        }
    }
}

CommonsDev/Controllers/ViewComponents/Layout/MenuTaskViewComponent.cs
using System.Collections.Generic;
using Commons.Models;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class MenuTaskViewComponent : ViewComponent
    {

        public MenuTaskViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            var messages = GetData();
            return View("LayoutMenuTask", messages);
        }

        private List<Message> GetData()
        {
            var messages = new List<Message>();
            messages.Add(new Message
            {
                Id = 1,
                ShortDesc = "Design some buttons",
                URLPath = "#",
                Percentage = 20,
            });

            return messages;
        }
    }
}

CommonsDev/Controllers/ViewComponents/Layout/MenuUserViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class MenuUserViewComponent : ViewComponent
    {

        public MenuUserViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            return View("LayoutMenuUser");
        }
    }
}

CommonsDev/Controllers/ViewComponents/Layout/PageHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class PageHeaderViewComponent : ViewComponent
    {

        public PageHeaderViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            return View("LayoutPageHeader");
        }
    }
}

CommonsDev/Controllers/ViewComponents/Layout/SidebarViewComponent.cs
using System;
using System.Collections.Generic;
using Commons.Extensions;
using Commons.Helpers;
using Commons.Models;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class SidebarViewComponent : ViewComponent
    {
        private List<SidebarMenu> sidebars = new List<SidebarMenu>();

        public IViewComponentResult Invoke(string filter)
        {
            //you can do the access rights checking here by using session, user, and/or filter parameter

            if (!User.Identity.IsAuthenticated) return View("LayoutSidebar", sidebars);

            sidebars.Add(MenuHelpers.AddHeader("Menú Principal"));

            sidebars.Add(MenuHelpers.AddModule("Funciones", "/SecurityFunctions/", "fa  fa-warning"));
            sidebars.Add(MenuHelpers.AddModule("Roles", "/SecurityRoles/", "fa  fa-warning"));
            sidebars.Add(MenuHelpers.AddModule("Institutos", "/Institutes/", "fa  fa-gear"));
            sidebars.Add(MenuHelpers.AddModule("Institutos Old", "/Institutes/DataTable", "fa  fa-gear"));
            sidebars.Add(MenuHelpers.AddModule("Modals", "/Home/About", "fa  fa-gear"));


            if (HttpContext.UserHasRoute("/TestClasses/Index"))
            {
                sidebars.Add(MenuHelpers.AddModule("TestClass", "/TestClasses/", "fa  fa-gear"));
            }

            var luke = MenuHelpers.AddTree("Luke");

            luke.TreeChild = new List<SidebarMenu>()
            {
                MenuHelpers.AddModule("Bullet", "/Home/Privacy"),
                MenuHelpers.AddModule("Bullet", "/Home/About")
            };



            var vader = MenuHelpers.AddTree("Vader");
            
            vader.TreeChild = new List<SidebarMenu>()
            {
                luke
            };
            

            sidebars.Add(vader);

            foreach (SidebarMenu sidebar in sidebars)
            {
                
            }

            return View("LayoutSidebar", sidebars);
        }


        public void AddModule(string text, string urlPath, string iconClassName = "fa fa-circle-o",
            Tuple<int, int, int> counter = null)
        {
            sidebars.Add(MenuHelpers.AddModule(text, urlPath, iconClassName, counter));
        }

        public void AddModuleIf(string text, string urlPath, string iconClassName = "fa fa-circle-o",
            Tuple<int, int, int> counter = null)
        {
            if (!HttpContext.UserHasRoute(urlPath)) return;
            sidebars.Add(MenuHelpers.AddModule(text, urlPath, iconClassName, counter));
        }



    }
}

CommonsDev/Views/Shared/_Layout.cshtml
@{
    var applicationName = "Change name in _Layout";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@applicationName - @ViewBag.Title</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @await Component.InvokeAsync("RegisterCommonsOffline")

    <script src="~/js/site.js"></script>


</head>



@*BODY TAG OPTIONS:
    =================
    Apply one or more of the following classes to get the
    desired effect
    |---------------------------------------------------------|
    | SKINS         | skin-blue                               |
    |               | skin-black                              |
    |               | skin-purple                             |
    |               | skin-yellow                             |
    |               | skin-red                                |
    |               | skin-green                              |
    |---------------------------------------------------------|
    |LAYOUT OPTIONS | fixed                                   |
    |               | layout-boxed                            |
    |               | layout-top-nav                          |
    |               | sidebar-collapse                        |
    |               | sidebar-mini                            |
    |---------------------------------------------------------|*@

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        @await Component.InvokeAsync("Header")
        <!-- Left side column. contains the logo and sidebar -->
        @await Component.InvokeAsync("Sidebar")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                @await Component.InvokeAsync("PageHeader")
                @await Component.InvokeAsync("Breadcrumb")
            </section>
            <!-- Main content -->
            <section class="content container-fluid">
                @await Component.InvokeAsync("PageAlert")
                <section class="content no-padding">
                    @RenderBody()
                </section>
                @await Component.InvokeAsync("ConfirmModal")
            </section>
        </div>
        @await Component.InvokeAsync("Footer")
        @await Component.InvokeAsync("ControlSidebar")
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

CommonsDev/Views/Shared/_ModalError.cshtml
@model string

<div class="row">
    <div class="col-md-12 text-center">
        <p class="text-danger">@Model</p>
    </div>
</div>